### ISSUE TITLE
Class and Naming details

### ISSUE THREAD

**Issue by krainboltgreene** [nivram80/distance_conv#1]
So the underlying logic of your conversion classes are perfect. You placed everything correctly, but I feel like the naming you've used doesn't fit with regular ruby/OOP usage. I'll give you some examples, but first here's the original code:

``` ruby
class MilesToKm
  attr_accessor :miles_to_km

  def initialize(miles)
    @miles = miles.to_f
  end

  def miles_to_km
    @miles * 1.609344
  end
end

class KmToMiles
  attr_accessor :km_to_miles

  def initialize(kilometers)
    @kilometers = kilometers.to_f
  end

  def km_to_miles
    @kilometers * 0.621371
  end
end
```

The concept these classes solve is pretty simple: I want to take X unit and turn it into Y unit, and vice versa. X unit in this case is a Mile and Y unit is a Kilometer. Amusingly we would probably in the long haul actually want to turn these into Inch and Meter, because those are the base unit names, but we'll eschew that kind of architecture in these for brevity.

Now that we know what the names of our X and Y are, we'll make classes containing those concepts:

``` ruby
class Kilometer

end

class Mile

end
```

We'll need setup methods so that we can conceptualize an Integer as either of these units (lets do Kilometer first):

``` ruby
class Kilometer
  def initializer(value)
    @value = value
  end
end
```

Now the value we pass to a newly created `Kilometer` object will record the value. We're not done yet though, because we still need that conversion method. Previously you used `km_to_miles` but we already know the original unit. We should use the form defined by Ruby core for things like turning an Array into a String, and String to a Symbol: `to_[class]`.

``` ruby
class Kilometer
  def initializer(value)
    @value = value
  end

  def to_miles
    @value * 0.621371
  end
end
```

That's great, now we can use it like this:

``` ruby
Kilometer.new(10).to_miles #=> 6.21371
```

But we're not done yet, because we've got some cleanup. For instance, that hanging float in the code is called a "Magic Number". In that could be hard for someone to come into the code and know what that number represents, especially if we have to use it in other places. Let's fix that:

``` ruby
class Kilometer
  PER_MILE_VALUE = 0.621371

  def initializer(value)
    @value = value
  end

  def to_miles
    @value * PER_MILE_VALUE
  end
end
```

The other problem is that we're just using instance variables. What happens when we want to change how the value is accessed or do post-process formatting on the value (like fractions)? Whoops, we just allowed for code duplication! Lets prevent that:

``` ruby
class Kilometer
  PER_MILE_VALUE = 0.621371

  attr_accessor :value

  def initializer(value)
    self.value = value
  end

  def value=(v)
    @value = v.to_f
  end

  def to_miles
    value * PER_MILE_VALUE
  end
end
```

Now if we wanted to we could redefine the getter and setter method for `@value`. Lets look at the changes with both classes:

``` ruby
class Kilometer
  PER_MILE_VALUE = 0.621371

  attr_accessor :value

  def initializer(value)
    self.value = value
  end

  def value=(v)
    @value = v.to_f
  end

  def to_miles
    value * PER_MILE_VALUE
  end
end

class Mile
  PER_KILOMETER_VALUE = 1.609344

  attr_accessor :value

  def initializer(value)
    self.value = value
  end

  def value=(v)
    @value = v.to_f
  end

  def to_kilometers
    value * PER_KILOMETER_VALUE
  end
end
```

Great, but it's obvious we have some code duplication. Turns out Ruby's built in library has a fun class called `Struct` that can save us some space:

``` ruby
class Kilometer < Struct.new(:value)
  PER_MILE_VALUE = 0.621371

  def value=(v)
    @value = v.to_f
  end

  def to_miles
    value * PER_MILE_VALUE
  end
end

class Mile < Struct.new(:value)
  PER_KILOMETER_VALUE = 1.609344

  def value=(v)
    @value = v.to_f
  end

  def to_kilometers
    value * PER_KILOMETER_VALUE
  end
end
```

Tada! Now you could go a little further here and extract the struct/per constant behavior:

``` ruby
class Measurement < Struct.new(:value)
  MILE_PER_KILOMETER = 1.609344
  KILOMETER_PER_MILE = 0.621371

  def value=(v)
    @value = v.to_f
  end
end

class Kilometer < Measurement
  def to_miles
    value * KILOMETER_PER_MILE
  end
end

class Mile < Measurement
  def to_kilometers
    value * MILE_PER_KILOMETER
  end
end
```

But on code so small it's hard to see the benefits. Mainly this makes testing that much easier:

``` ruby
class Measurement < Struct.new(:value)
  MILE_PER_KILOMETER = 1.609344
  KILOMETER_PER_MILE = 0.621371

  def value=(v)
    @value = v.to_f
  end
end

class Kilometer < Measurement
  def to_miles
    value * KILOMETER_PER_MILE
  end
end

class Mile < Measurement
  def to_kilometers
    value * MILE_PER_KILOMETER
  end
end

require 'minitest/autorun'
class TestKilometer < MiniTest::Unit::TestCase
  def setup
    @kilometer = Kilometer.new(100)
  end

  def test_to_miles
    expected = 62.137100000000004
    actual = @kilometer.to_miles
    assert_equal expected, actual
  end

  def test_value=
    expected = 100.0
    actual = @kilometer.value
    assert_equal expected, actual
  end
end
```

Floats actually suck to work with though, because Floating Point arithmatic is different on each processor architecture, so avoid it if you can.

**Comment by DouglasAllen** [comment]
You don't need to avoid floats. Just use a different approach. Try something like an Epsilon. Epsilon is how close to the answer do you want to let it deviate. e = .000001 or something like that. Yes I agree. You might never get the same answer with a Float type. But it can be used. It is a computer science concept.
About as close as I can explain it is here. http://en.wikipedia.org/wiki/Machine_epsilon
The reason I'm concerned with this is that Ruby needs to start getting included into Computer Science code. It's not used often enough to help Rubyists learn Computer Science.
